import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import download from 'downloadjs';

export default function Home() {
  const [inputvalue, setInputValue] = useState('');

  return (
    <div className={styles.container}>
      <Head>
        <title>Youtube Downloader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://logos-world.net/wp-content/uploads/2020/04/YouTube-Emblem.png" />
      </Head>
      <div className="container">
            <h3 className={styles.animatecharcter}>Youtube Video Downloader</h3>
      </div> 
      <div>
        <label className={styles.search}>Search Here, </label>
        <input className={styles.inputBox} type="text" onChange={(e)=>{
          setInputValue(e.target.value);
        }} name="url"  placeholder='https://www.youtube.com/watch?v=B31LgI4Y4DQ&t=1213s' 
        />
        <button onClick={async()=>{
          console.log(inputvalue);
          const res = await fetch(
            "/api/download",
            {
              method: "POST",
              headers: {
                "Content-disposition": "attachment; filename=Video.mp4",
              },
              body: JSON.stringify({
                url: inputvalue
              })
            }
         
          )
          const blob = await res.blob();
          download(blob, "Video.mp4");
        }} className={styles.submit}>
          Download
        </button>
      </div>
    </div>
  )
}
